package vista;

/**
 *
 * @author aleja
 */
public class VistaVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaVentas
     */
    public VistaVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sp_cantidad = new javax.swing.JSpinner();
        txt_id = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_ventas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_busqueda = new javax.swing.JTable();
        btn_pagar = new javax.swing.JButton();
        txt_total = new javax.swing.JTextField();
        cb_pago = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lbl_resultado = new javax.swing.JLabel();
        cb_clientes = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_puntosdisponibles = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_totalfinal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_puntos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_pago = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_cambio = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_buscar.setBackground(new java.awt.Color(255, 102, 102));
        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 83, -1, 37));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("VENTAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 22, -1, -1));

        btn_eliminar.setBackground(new java.awt.Color(255, 102, 102));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, 37));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("Codigo de barras");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 80, -1, -1));

        jLabel4.setText("Cantidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 80, -1, -1));

        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 64, -1, -1));
        getContentPane().add(sp_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 102, -1, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, 50, -1));
        getContentPane().add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 102, 140, -1));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 91, 180, -1));

        jLabel6.setText("TOTAL:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        tabla_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio", "Total", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_ventas);
        if (tabla_ventas.getColumnModel().getColumnCount() > 0) {
            tabla_ventas.getColumnModel().getColumn(1).setMaxWidth(75);
            tabla_ventas.getColumnModel().getColumn(2).setMaxWidth(100);
            tabla_ventas.getColumnModel().getColumn(3).setMaxWidth(100);
            tabla_ventas.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 480, 365));

        tabla_busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_busqueda);
        if (tabla_busqueda.getColumnModel().getColumnCount() > 0) {
            tabla_busqueda.getColumnModel().getColumn(0).setMaxWidth(40);
            tabla_busqueda.getColumnModel().getColumn(2).setMaxWidth(75);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 124, 279, 136));

        btn_pagar.setBackground(new java.awt.Color(255, 102, 102));
        btn_pagar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_pagar.setForeground(new java.awt.Color(255, 255, 255));
        btn_pagar.setText("Pagar");
        getContentPane().add(btn_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 116, 41));

        txt_total.setEditable(false);
        txt_total.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_total.setText("0");
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 151, 34));

        cb_pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        getContentPane().add(cb_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 170, -1));

        jLabel7.setText("Metodo de pago:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        lbl_resultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_resultado.setForeground(new java.awt.Color(255, 0, 51));
        lbl_resultado.setText("xd");
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 280, 50));

        getContentPane().add(cb_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 278, 111, -1));

        jLabel8.setText("Cliente:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLabel9.setText("puntos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 281, -1, -1));

        txt_puntosdisponibles.setEditable(false);
        txt_puntosdisponibles.setText("0");
        getContentPane().add(txt_puntosdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 278, 53, -1));

        jLabel10.setText("TOTAL FINAL:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 364, 83, -1));

        txt_totalfinal.setEditable(false);
        txt_totalfinal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_totalfinal.setText("0");
        getContentPane().add(txt_totalfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 352, 154, 39));

        jLabel11.setText("Puntos a usar:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 315, -1, -1));

        txt_puntos.setText("0");
        getContentPane().add(txt_puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 312, 80, -1));

        jLabel12.setText("PAGO:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 429, -1, -1));

        txt_pago.setText("0");
        getContentPane().add(txt_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 426, 89, -1));

        jLabel13.setText("CAMBIO:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 429, -1, -1));

        txt_cambio.setEditable(false);
        txt_cambio.setText("0");
        getContentPane().add(txt_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 426, 86, -1));

        btn_agregar.setBackground(new java.awt.Color(255, 102, 102));
        btn_agregar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Añadir");
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 92, 37));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregar;
    public javax.swing.JButton btn_buscar;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JButton btn_pagar;
    public javax.swing.JComboBox<String> cb_clientes;
    public javax.swing.JComboBox<String> cb_pago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbl_resultado;
    public javax.swing.JSpinner sp_cantidad;
    public javax.swing.JTable tabla_busqueda;
    public javax.swing.JTable tabla_ventas;
    public javax.swing.JTextField txt_cambio;
    public javax.swing.JTextField txt_codigo;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_pago;
    public javax.swing.JTextField txt_puntos;
    public javax.swing.JTextField txt_puntosdisponibles;
    public javax.swing.JTextField txt_total;
    public javax.swing.JTextField txt_totalfinal;
    // End of variables declaration//GEN-END:variables
}
