/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author aleja
 */
public class VistaInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaInventario
     */
    public VistaInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        cb_categoria = new javax.swing.JComboBox<>();
        txt_nombre = new javax.swing.JTextField();
        txt_codigobarras = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        cb_mes = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb_anio = new javax.swing.JComboBox<>();
        sp_existencias = new javax.swing.JSpinner();
        txt_costo = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_inventario = new javax.swing.JTable();
        chb_caducidad = new javax.swing.JCheckBox();
        btn_select = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(820, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Inventario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 30, -1, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 77, -1, -1));

        jLabel3.setText("Categoria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 77, -1, -1));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 77, -1, -1));

        jLabel5.setText("Codigo de barras");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 77, -1, -1));

        jLabel6.setText("Precio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 77, -1, -1));

        jLabel7.setText("Caducidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 29, -1, -1));

        jLabel8.setText("Existencias");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 77, -1, -1));

        jLabel9.setText("Costo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 77, -1, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 99, 50, -1));

        getContentPane().add(cb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 99, 100, -1));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 99, 100, -1));
        getContentPane().add(txt_codigobarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 99, 100, -1));
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 99, 50, -1));

        cb_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cb_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 99, 50, -1));

        jLabel10.setText("Mes");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 77, -1, -1));

        jLabel11.setText("Año");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 77, -1, -1));

        getContentPane().add(cb_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 99, 61, -1));
        getContentPane().add(sp_existencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 99, 50, -1));
        getContentPane().add(txt_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 99, 70, -1));

        btn_agregar.setBackground(new java.awt.Color(255, 102, 102));
        btn_agregar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agregar");
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 139, 110, 40));

        btn_buscar.setBackground(new java.awt.Color(255, 102, 102));
        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 110, 40));

        btn_actualizar.setBackground(new java.awt.Color(255, 102, 102));
        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setText("Actualizar");
        getContentPane().add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, 40));

        btn_borrar.setBackground(new java.awt.Color(255, 102, 102));
        btn_borrar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_borrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_borrar.setText("Borrar");
        getContentPane().add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 110, 40));

        tabla_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Nombre", "Codigo", "Precio", "Caducidad", "Existencias", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_inventario);
        if (tabla_inventario.getColumnModel().getColumnCount() > 0) {
            tabla_inventario.getColumnModel().getColumn(0).setMaxWidth(50);
            tabla_inventario.getColumnModel().getColumn(1).setMaxWidth(100);
            tabla_inventario.getColumnModel().getColumn(2).setMaxWidth(300);
            tabla_inventario.getColumnModel().getColumn(3).setMaxWidth(200);
            tabla_inventario.getColumnModel().getColumn(4).setMaxWidth(100);
            tabla_inventario.getColumnModel().getColumn(5).setMaxWidth(120);
            tabla_inventario.getColumnModel().getColumn(6).setMaxWidth(50);
            tabla_inventario.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 776, 370));

        chb_caducidad.setText("No aplica");
        getContentPane().add(chb_caducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 51, -1, -1));

        btn_select.setText("Select");
        getContentPane().add(btn_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 90, -1));

        btn_limpiar.setText("Limpiar");
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_actualizar;
    public javax.swing.JButton btn_agregar;
    public javax.swing.JButton btn_borrar;
    public javax.swing.JButton btn_buscar;
    public javax.swing.JButton btn_limpiar;
    public javax.swing.JButton btn_select;
    public javax.swing.JComboBox<String> cb_anio;
    public javax.swing.JComboBox<String> cb_categoria;
    public javax.swing.JComboBox<String> cb_mes;
    public javax.swing.JCheckBox chb_caducidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSpinner sp_existencias;
    public javax.swing.JTable tabla_inventario;
    public javax.swing.JTextField txt_codigobarras;
    public javax.swing.JTextField txt_costo;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
